### ISSUE TITLE
Failed to create image registry with Swift storage on s390x

### ISSUE THREAD

**Issue by gyohuangxin** [openshift/image-registry#243]
I'm trying to deploy OCP 4.5 on s390x openstack platform, but image registry with Swift storage cannot be created with error message about x509 certificate:

```
$ oc logs image-registry-57446c46b7-2zdpf -n openshift-image-registry
time="2020-08-04T06:37:29.698512303Z" level=info msg="start registry" distribution_version=v2.6.0+unknown go.version=go1.13.4 openshift_version=4.5.0-202006291853.p0-861af92
time="2020-08-04T06:37:29.700502106Z" level=info msg="caching project quota objects with TTL 1m0s" go.version=go1.13.4
panic: Swift authentication failed: Post https://xx.xx.xx.xx:5000/v3/auth/tokens: x509: certificate signed by unknown authority

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x1aac9e0, 0xc0000440e0, 0xc000614e00, 0xc0005f2f60)
	/go/src/github.com/openshift/image-registry/vendor/github.com/docker/distribution/registry/handlers/app.go:127 +0x2ef6
github.com/openshift/image-registry/pkg/dockerregistry/server/supermiddleware.NewApp(0x1aac9e0, 0xc0000440e0, 0xc000614e00, 0x1ab5c60, 0xc00067ccf0, 0x1abe9c0)
	/go/src/github.com/openshift/image-registry/pkg/dockerregistry/server/supermiddleware/app.go:96 +0x86
github.com/openshift/image-registry/pkg/dockerregistry/server.NewApp(0x1aac9e0, 0xc0000440e0, 0x1a78020, 0xc0006821c8, 0xc000614e00, 0xc000362320, 0x0, 0x0, 0xc0001202d0, 0x1658760)
	/go/src/github.com/openshift/image-registry/pkg/dockerregistry/server/app.go:138 +0x2a2
github.com/openshift/image-registry/pkg/cmd/dockerregistry.NewServer(0x1aac9e0, 0xc0000440e0, 0xc000614e00, 0xc000362320, 0x0, 0x0, 0x1ae7c80)
	/go/src/github.com/openshift/image-registry/pkg/cmd/dockerregistry/dockerregistry.go:210 +0x1bc
github.com/openshift/image-registry/pkg/cmd/dockerregistry.Execute(0x1a67ea0, 0xc000130020)
	/go/src/github.com/openshift/image-registry/pkg/cmd/dockerregistry/dockerregistry.go:164 +0x9da
main.main()
	/go/src/github.com/openshift/image-registry/cmd/dockerregistry/main.go:93 +0x454
```

clouds.yaml:
```
clouds:
  openstack:
    auth:
      auth_url: https://xxxx:5000/v3
      username: root
      project_name: ibm-default
      project_id: e4363f795191482fb7478a6fd1852da0
      domain_name: Default
      password: dfltpass
      user_domain_name: Default
    region_name: "RegionOne"
    cacert: /etc/pki/tls/certs/icic.crt
    interface: "public"
    identity_api_version: 3
```

```
$ oc edit configs.imageregistry.operator.openshift.io
  storage:
    swift:
      authURL: https://xx.xx.xx.xx:5000/v3
      authVersion: "3"
      container: ocpcic-d5lj8-image-registry-cijqbvlwdundbvrdkwniwqjytqsgjcqxks
      domain: Default
      regionName: RegionOne
      tenant: ibm-default
      tenantID: e4363f795191482fb7478a6fd1852da0
  storageManaged: true
```
