### ISSUE TITLE
allowedRegistriesForImport Behavior

### ISSUE THREAD

**Issue by KyWa** [openshift/image-registry#322]
# Issue
Recently working in a somewhat disconnected environment, although the use of `ImageContentSourcePolicy` objects functions through a Proxy instance, we have seen "odd" behavior in the `allowedRegistriesForImport` and `registrySources.insecureRegistries`. 

When attempting a cluster version upgrade, the `clusterversion` pod had logs saying `Forbidden: registry "quay.io" not allowed by whitelist: "quay.io/openshift-release-dev:443"` similar to what is seen in this Solution from access.redhat.com: https://access.redhat.com/solutions/6531701. We have `quay.io/openshift-release-dev` in our `ImageContentSourcePolicy` to pull from our proxy instance and no other OpenShift images have issues except during the cluster upgrade when updating/creating an `ImageStream`. I looked at the manifests and they were targeting the digest of the image, so the `ImageContentSourcePolicy` should have triggered, but it did not (separate question in that). 

To attempt to get around this, we updated the below config (and waiting for the nodes to rollout the new config) and see where we stand, but we were met with the same error as before.

Here is the configuration (trimmed down of course) that we were using:

```
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
spec:
  allowedRegistriesForImport: 
  - domainName: quay.io
    insecure: true
  - domainName: someotherregistries.com
    insecure: true
  registrySources:
    insecureRegistries:
    - quay.io
    - someotherregistries.com
```

We are aware that `quay.io` is not an insecure registry, this config was just copied over from one of the other lines in the list and wasn't changed to `false`. I did a manual test via `oc import-image` to the exact same digest (quay.io/openshift-release-dev@sha256:something) and did at least get the same error as the `clusterversion` pod had, which was expected. When we updated the above config to state `insecure=false` for `quya.io` and let the nodes roll, it was able to get past the issue we were seeing and was then part of the "whitelist". Still strange considering the manifests being applied were targeting the a digest which should have had the `ImageContentSourcePolicy` trigger.

I don't know the codebase for this repo all that well, but I did go looking around for how it handles the `allowedRegistriesForImport` and nothing seemed to be "unique" with how `quay.io` was handled.

# Expected Behavior 

`quay.io` "working" as expected even with `insecure=true` listed in the `image.config` CRD for OpenShift as being on the allowed list. 

This was tested on OCP 4.6 during the -> 4.7 upgrade (same issue was seen for a different ImageStream from the Samples operator with identical issue looking back now at least [`quay.io/openshift-release-dev`]) and the -> 4.8 upgrade.
